/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncmonitorRouteImport } from './routes/syncmonitor'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehouseTransactionsRouteImport } from './routes/warehouse.transactions'
import { Route as WarehouseSyncRouteImport } from './routes/warehouse.sync'
import { Route as WarehouseHistoryRouteImport } from './routes/warehouse.history'
import { Route as DashboardEcommerceRouteImport } from './routes/dashboard.ecommerce'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSyncEngineRouteImport } from './routes/admin.sync-engine'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminConfigRouteImport } from './routes/admin.config'

const SyncmonitorRoute = SyncmonitorRouteImport.update({
  id: '/syncmonitor',
  path: '/syncmonitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseTransactionsRoute = WarehouseTransactionsRouteImport.update({
  id: '/warehouse/transactions',
  path: '/warehouse/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseSyncRoute = WarehouseSyncRouteImport.update({
  id: '/warehouse/sync',
  path: '/warehouse/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseHistoryRoute = WarehouseHistoryRouteImport.update({
  id: '/warehouse/history',
  path: '/warehouse/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEcommerceRoute = DashboardEcommerceRouteImport.update({
  id: '/dashboard/ecommerce',
  path: '/dashboard/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSyncEngineRoute = AdminSyncEngineRouteImport.update({
  id: '/admin/sync-engine',
  path: '/admin/sync-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/channels': typeof ChannelsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/syncmonitor': typeof SyncmonitorRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync-engine': typeof AdminSyncEngineRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ecommerce': typeof DashboardEcommerceRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/sync': typeof WarehouseSyncRoute
  '/warehouse/transactions': typeof WarehouseTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/channels': typeof ChannelsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/syncmonitor': typeof SyncmonitorRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync-engine': typeof AdminSyncEngineRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ecommerce': typeof DashboardEcommerceRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/sync': typeof WarehouseSyncRoute
  '/warehouse/transactions': typeof WarehouseTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/channels': typeof ChannelsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/syncmonitor': typeof SyncmonitorRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/sync-engine': typeof AdminSyncEngineRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/ecommerce': typeof DashboardEcommerceRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/sync': typeof WarehouseSyncRoute
  '/warehouse/transactions': typeof WarehouseTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/channels'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/products'
    | '/syncmonitor'
    | '/admin/config'
    | '/admin/logs'
    | '/admin/sync-engine'
    | '/admin/users'
    | '/dashboard/ecommerce'
    | '/warehouse/history'
    | '/warehouse/sync'
    | '/warehouse/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/channels'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/products'
    | '/syncmonitor'
    | '/admin/config'
    | '/admin/logs'
    | '/admin/sync-engine'
    | '/admin/users'
    | '/dashboard/ecommerce'
    | '/warehouse/history'
    | '/warehouse/sync'
    | '/warehouse/transactions'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/channels'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/products'
    | '/syncmonitor'
    | '/admin/config'
    | '/admin/logs'
    | '/admin/sync-engine'
    | '/admin/users'
    | '/dashboard/ecommerce'
    | '/warehouse/history'
    | '/warehouse/sync'
    | '/warehouse/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ChannelsRoute: typeof ChannelsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  SyncmonitorRoute: typeof SyncmonitorRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSyncEngineRoute: typeof AdminSyncEngineRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardEcommerceRoute: typeof DashboardEcommerceRoute
  WarehouseHistoryRoute: typeof WarehouseHistoryRoute
  WarehouseSyncRoute: typeof WarehouseSyncRoute
  WarehouseTransactionsRoute: typeof WarehouseTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syncmonitor': {
      id: '/syncmonitor'
      path: '/syncmonitor'
      fullPath: '/syncmonitor'
      preLoaderRoute: typeof SyncmonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/transactions': {
      id: '/warehouse/transactions'
      path: '/warehouse/transactions'
      fullPath: '/warehouse/transactions'
      preLoaderRoute: typeof WarehouseTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/sync': {
      id: '/warehouse/sync'
      path: '/warehouse/sync'
      fullPath: '/warehouse/sync'
      preLoaderRoute: typeof WarehouseSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/history': {
      id: '/warehouse/history'
      path: '/warehouse/history'
      fullPath: '/warehouse/history'
      preLoaderRoute: typeof WarehouseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ecommerce': {
      id: '/dashboard/ecommerce'
      path: '/dashboard/ecommerce'
      fullPath: '/dashboard/ecommerce'
      preLoaderRoute: typeof DashboardEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sync-engine': {
      id: '/admin/sync-engine'
      path: '/admin/sync-engine'
      fullPath: '/admin/sync-engine'
      preLoaderRoute: typeof AdminSyncEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ChannelsRoute: ChannelsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  SyncmonitorRoute: SyncmonitorRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSyncEngineRoute: AdminSyncEngineRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardEcommerceRoute: DashboardEcommerceRoute,
  WarehouseHistoryRoute: WarehouseHistoryRoute,
  WarehouseSyncRoute: WarehouseSyncRoute,
  WarehouseTransactionsRoute: WarehouseTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
